In [19]:
from tensorflow.keras.preprocessing.text import one_hot


In [20]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [21]:
## Define the vocabulary size
voc_size = 10000

In [22]:
## One hot representation
onehot_repr = [one_hot(words, voc_size) for words in sent]
print(onehot_repr)

[[3357, 6600, 1781, 4630], [3357, 6600, 1781, 1355], [3357, 1463, 1781, 8035], [4088, 6542, 3600, 9605, 3760], [4088, 6542, 3600, 9605, 5638], [239, 3357, 7257, 1781, 5615], [2688, 2081, 9852, 9605]]


In [23]:
## Word embedding representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [24]:
import numpy as np

In [25]:
sent_length = 8
## Padding the sentences
embedded_docs = pad_sequences(onehot_repr, padding='pre', maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 3357 6600 1781 4630]
 [   0    0    0    0 3357 6600 1781 1355]
 [   0    0    0    0 3357 1463 1781 8035]
 [   0    0    0 4088 6542 3600 9605 3760]
 [   0    0    0 4088 6542 3600 9605 5638]
 [   0    0    0  239 3357 7257 1781 5615]
 [   0    0    0    0 2688 2081 9852 9605]]


In [26]:
## feature representation
dim = 10


In [27]:
model = Sequential()
model.add(Embedding(voc_size, dim, input_length=sent_length))
model.compile('adam', 'mse')

In [28]:
model.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_4 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [31]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step


array([[[ 7.16846064e-03, -2.71809697e-02,  3.07876989e-03,
         -3.73907089e-02,  2.61738785e-02,  9.48138162e-03,
          4.48595770e-02,  4.81866859e-02, -2.45017763e-02,
         -7.05239922e-03],
        [ 7.16846064e-03, -2.71809697e-02,  3.07876989e-03,
         -3.73907089e-02,  2.61738785e-02,  9.48138162e-03,
          4.48595770e-02,  4.81866859e-02, -2.45017763e-02,
         -7.05239922e-03],
        [ 7.16846064e-03, -2.71809697e-02,  3.07876989e-03,
         -3.73907089e-02,  2.61738785e-02,  9.48138162e-03,
          4.48595770e-02,  4.81866859e-02, -2.45017763e-02,
         -7.05239922e-03],
        [ 7.16846064e-03, -2.71809697e-02,  3.07876989e-03,
         -3.73907089e-02,  2.61738785e-02,  9.48138162e-03,
          4.48595770e-02,  4.81866859e-02, -2.45017763e-02,
         -7.05239922e-03],
        [ 9.94258001e-03,  3.92735042e-02, -1.35070197e-02,
          3.97242643e-02,  2.56167725e-03,  3.17083634e-02,
         -1.60700679e-02, -4.38463688e-03,  2.306953

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 150ms/step


array([[[ 0.00716846, -0.02718097,  0.00307877, -0.03739071,
          0.02617388,  0.00948138,  0.04485958,  0.04818669,
         -0.02450178, -0.0070524 ],
        [ 0.00716846, -0.02718097,  0.00307877, -0.03739071,
          0.02617388,  0.00948138,  0.04485958,  0.04818669,
         -0.02450178, -0.0070524 ],
        [ 0.00716846, -0.02718097,  0.00307877, -0.03739071,
          0.02617388,  0.00948138,  0.04485958,  0.04818669,
         -0.02450178, -0.0070524 ],
        [ 0.00716846, -0.02718097,  0.00307877, -0.03739071,
          0.02617388,  0.00948138,  0.04485958,  0.04818669,
         -0.02450178, -0.0070524 ],
        [ 0.00994258,  0.0392735 , -0.01350702,  0.03972426,
          0.00256168,  0.03170836, -0.01607007, -0.00438464,
          0.02306953, -0.0034076 ],
        [ 0.02913827, -0.02173475, -0.01304734, -0.01068853,
          0.04684396, -0.0355835 ,  0.01068475,  0.03058714,
         -0.02819401, -0.02532109],
        [-0.02110875, -0.00131413, -0.04521547,  0.0

In [32]:
print(embedded_docs[0])

[   0    0    0    0 3357 6600 1781 4630]
